### ISSUE TITLE
Add license file?

### ISSUE THREAD

**Issue by sebastientromp** [alimate/Resource-Based-Error-Codes#1]
Hey! I love your approach to handling errors and keeping the control under each resource.

I would like to use bits of this for my (commercial) application, but can't do so without an explicit license (I guess, to be honest I'm not very well versed in this stuff).
Would you mind adding a license file so we know what we can do with the code?

Thanks!

**Comment by alimate** [comment]
I have no idea how I missed this issue for such a long time. I'm genuinely sorry for the delay. Feel free to copy the code base. Also, you can use the starter I developed for the same idea.

Again, I'm terribly sorry for the delayed answer.

**Comment by sebastientromp** [comment]
Thanks a lot!
